var LOTTEON_REMOTE_TASK={id:'ISSUE79-NOMATCH22-LATEST-RECHECK-v2',title:'NO_MATCH 22 다중상태 + 최신카드 + 국제운송료 재검수 PREVIEW',enabled:true,statusSheet:'ISSUE79_최신재검수상태'};
var I79V='v2.0-ISSUE79-NOMATCH22-MULTISTATUS-CARD-INTL-FREIGHT-READONLY';
var I79D='ISSUE79_NOMATCH22_최신재검수',I79S='ISSUE79_최신재검수상태';
var I79CORE=['매출데이터_붙여넣기','부가세_신고자료','부가세_카드매칭검증','부가세_기간별','카드사용내역_붙여넣기','카드_마스터'];
function runLotteonRemoteTaskStartRemote_(){return i79runV2_();}
function runLotteonRemoteTaskContinueRemote_(){return i79runV2_();}
function i79runV2_(){var ss=SpreadsheetApp.getActive(),before={};try{
  i79status_(ss,[['version',I79V],['상태','RUNNING'],['단계','GUARD'],['메시지','NO_MATCH 22 다중 상태컬럼 + 최신 카드정보 + 국제운송료 기준 재검수 중']]);
  I79CORE.forEach(function(n){var sh=ss.getSheetByName(n);if(!sh)throw new Error('핵심 시트 누락: '+n);before[n]=i79sig_(sh);});
  var card=i79readCard_(ss.getSheetByName('부가세_카드매칭검증'));
  if(card.rows.length!==1355||(card.stats.MATCHED||0)!==835||(card.stats.NON_CARD||0)!==498||(card.stats.AMBIGUOUS||0)!==0||(card.stats.NO_MATCH||0)!==22||card.purchase!==105762969)throw new Error('현재 카드검증 baseline 불일치 '+JSON.stringify({n:card.rows.length,s:card.stats,p:card.purchase}));
  var targets=card.rows.filter(function(x){return x.status==='NO_MATCH';});if(targets.length!==22)throw new Error('NO_MATCH 22 guard 실패');
  var src=i79readOrderSourceV2_(ss.getSheetByName('매출데이터_붙여넣기'));
  var hist=i79canon_(i79readHist_(ss.getSheetByName('카드사용내역_붙여넣기'))),used=i79used_(card.rows);
  var out=[],sum={cancelComplete:0,intlRule:0,purchaseRule:0,safeIntl:0,safePurchase:0,multi:0,used:0,conflict:0,noCandidate:0,intlMissing:0,intlMulti:0,cancelLikeReview:0,otherReview:0};
  targets.forEach(function(o){
    var sm=src.map[o.orderNo]||{statuses:[],statusDetails:[],fees:[]};
    var statusText=sm.statuses.join(' / '),statusDetail=sm.statusDetails.join(' / '),cancelComplete=i79cancelCompleteV2_(sm.statuses),cancelLike=i79cancelLike_(statusText),fees=i79distinctAbs_(sm.fees),targetType='PURCHASE',targetAmount=o.purchase,verdict='',windowText='-1~+7';
    if(cancelComplete){sum.cancelComplete++;if(fees.length===1&&fees[0]>0){targetType='INTL_FREIGHT';targetAmount=fees[0];windowText='-30~+30';sum.intlRule++;}else if(!fees.length){verdict='CANCEL_INTL_FEE_MISSING';sum.intlMissing++;}else{verdict='CANCEL_INTL_FEE_MULTI';sum.intlMulti++;}}
    else{sum.purchaseRule++;if(cancelLike){verdict='CANCEL_STATUS_REVIEW';sum.cancelLikeReview++;}}
    var cand=[];
    if(!verdict){
      cand=hist.filter(function(h){if(h.nonCard||h.fullyCanceled||!h.lotteEvidence||h.amount!==targetAmount)return false;var lag=i79days_(o.orderDate,h.date);return targetType==='INTL_FREIGHT'?Math.abs(lag)<=30:(lag>=-1&&lag<=7);});
      cand.sort(function(a,b){return Math.abs(i79days_(o.orderDate,a.date))-Math.abs(i79days_(o.orderDate,b.date));});
      var usedCand=cand.filter(function(h){return h.key&&used[h.key];}),conflict=cand.some(function(h){return i79payConflict_(o.payment,h.company);});
      if(cand.length===1&&!usedCand.length&&!conflict){verdict=targetType==='INTL_FREIGHT'?'SAFE_INTL_FEE_EXACT':'SAFE_PURCHASE_EXACT';if(targetType==='INTL_FREIGHT')sum.safeIntl++;else sum.safePurchase++;}
      else if(usedCand.length){verdict='USED_BY_OTHER';sum.used++;}
      else if(conflict){verdict='PAYMENT_CONFLICT';sum.conflict++;}
      else if(cand.length>1){verdict='MULTI_CANDIDATE';sum.multi++;}
      else{verdict='NO_CANDIDATE';sum.noCandidate++;}
    }
    if(!/^SAFE_/.test(verdict)&&['MULTI_CANDIDATE','USED_BY_OTHER','PAYMENT_CONFLICT','NO_CANDIDATE','CANCEL_INTL_FEE_MISSING','CANCEL_INTL_FEE_MULTI','CANCEL_STATUS_REVIEW'].indexOf(verdict)<0)sum.otherReview++;
    var best=cand[0]||{};
    out.push([o.business,o.account,o.orderDate,o.orderNo,o.purchase,o.payment,statusText,statusDetail,cancelComplete?'YES':'NO',fees.join('|'),targetType,targetAmount,windowText,verdict,cand.length,best.date||'',best.company||'',best.cardName||'',best.end4||'',best.approvalNo||'',best.amount||'',best.merchant||'',best.source||'',i79summary_(cand)]);
  });
  if(out.length!==22)throw new Error('진단행수 불일치 '+out.length);
  i79writeV2_(ss,out);
  var changed=[];I79CORE.forEach(function(n){var sh=ss.getSheetByName(n);if(!sh||i79sig_(sh)!==before[n])changed.push(n);});if(changed.length)throw new Error('READ-ONLY 위반: '+changed.join(', '));
  var safe=sum.safeIntl+sum.safePurchase,review=22-safe;
  i79status_(ss,[['version',I79V],['상태','PASS'],['단계','DONE'],['메시지','NO_MATCH 22 다중 상태컬럼 + 최신 카드정보 + 반품/취소 완료 국제운송료 기준 READ-ONLY 재검수 완료'],['NO_MATCH기준',22],['반품취소완료',sum.cancelComplete],['국제운송료기준적용',sum.intlRule],['일반매입금액기준',sum.purchaseRule],['SAFE_INTL_FEE_EXACT',sum.safeIntl],['SAFE_PURCHASE_EXACT',sum.safePurchase],['SAFE_합계',safe],['MULTI_CANDIDATE',sum.multi],['USED_BY_OTHER',sum.used],['PAYMENT_CONFLICT',sum.conflict],['NO_CANDIDATE',sum.noCandidate],['CANCEL_INTL_FEE_MISSING',sum.intlMissing],['CANCEL_INTL_FEE_MULTI',sum.intlMulti],['CANCEL_STATUS_REVIEW',sum.cancelLikeReview],['기타검토',sum.otherReview],['잔여검토',review],['국제운송료header',src.feeHeader],['상태headers',src.statusHeaders.join('|')],['핵심시트변경수',0],['오류',''],['완료시각',new Date().toISOString()]]);
  return{ok:true,done:true,version:I79V,safe:safe,review:review,cancelComplete:sum.cancelComplete};
 }catch(e){var m=String(e&&e.message?e.message:e);try{i79status_(ss,[['version',I79V],['상태','ERROR'],['단계','FAILED'],['메시지','Issue79 최신 재검수 v2 실패'],['오류',m],['완료시각',new Date().toISOString()]]);}catch(_e){}throw e;}}
function i79readOrderSourceV2_(sh){
  var v=sh.getDataRange().getValues(),d=sh.getDataRange().getDisplayValues(),hr=-1,order=-1,fee=-1,feeHeader='',statusCols=[],statusHeaders=[];
  for(var r=0;r<Math.min(v.length,30);r++){
    var h=v[r]||[],oi=i79ix_(h,['주문번호','마켓주문번호','상품주문번호']);if(oi<0)continue;var fi=i79feeIx_(h),sc=i79statusCols_(h);if(fi>=0&&sc.length){hr=r;order=oi;fee=fi;feeHeader=i79t_(h[fi]);statusCols=sc;statusHeaders=sc.map(function(x){return i79t_(h[x]);});break;}
  }
  if(hr<0||order<0)throw new Error('매출데이터 주문/상태/국제운송료 header 탐지 실패');
  var m={};for(var i=hr+1;i<v.length;i++){
    var no=i79t_(d[i][order]);if(!no)continue;if(!m[no])m[no]={statuses:[],statusDetails:[],fees:[]};
    statusCols.forEach(function(ix,idx){var st=i79t_(v[i][ix]);if(!st)return;if(m[no].statuses.indexOf(st)<0)m[no].statuses.push(st);var det=statusHeaders[idx]+'='+st;if(m[no].statusDetails.indexOf(det)<0)m[no].statusDetails.push(det);});
    var n=i79n_(v[i][fee]);if(n)m[no].fees.push(n);
  }
  return{map:m,feeHeader:feeHeader,statusHeaders:statusHeaders};
}
function i79statusCols_(h){var out=[],seen={};(h||[]).forEach(function(x,i){var c=i79c_(x);if(!c)return;var exact=['마켓주문상태','주문상태','상태','클레임상태','처리상태','취소상태','반품상태','환불상태','클레임처리상태'].some(function(a){return c===i79c_(a);});var dynamic=c.indexOf('상태')>=0&&/(마켓|주문|클레임|취소|반품|환불|처리)/.test(c);if((exact||dynamic)&&!seen[i]){seen[i]=1;out.push(i);}});return out;}
function i79cancelCompleteV2_(statuses){return (statuses||[]).some(function(s){var c=i79c_(s);return /(취소완료|취소처리완료|반품완료|반품처리완료|환불완료|환불처리완료|클레임완료|cancelled|canceled|returned|refunded)/i.test(c);});}
function i79readCard_(sh){var v=sh.getDataRange().getValues(),d=sh.getDataRange().getDisplayValues(),hr=i79header_(v,['주문번호','카드매칭상태']);if(hr<0)throw new Error('카드검증 header 탐지 실패');var h=v[hr],x={date:i79ix_(h,['주문일']),business:i79ix_(h,['사업자등록번호']),account:i79ix_(h,['쿠팡계정ID']),order:i79ix_(h,['주문번호']),purchase:i79ix_(h,['주문매입금액']),payment:i79ix_(h,['롯데결제수단']),status:i79ix_(h,['카드매칭상태']),company:i79ix_(h,['구매카드사']),name:i79ix_(h,['구매카드명']),end4:i79ix_(h,['카드번호끝4']),adate:i79ix_(h,['승인일']),approval:i79ix_(h,['승인번호']),aamount:i79ix_(h,['승인금액']),merchant:i79ix_(h,['가맹점명']),source:i79ix_(h,['원본파일'])},rows=[],stats={},p=0;for(var r=hr+1;r<v.length;r++){var no=x.order>=0?i79t_(d[r][x.order]):'';if(!no)continue;var st=i79t_(v[r][x.status]).toUpperCase(),amt=i79n_(v[r][x.purchase]);stats[st]=(stats[st]||0)+1;p+=amt;rows.push({business:i79t_(v[r][x.business]),account:i79t_(v[r][x.account]),orderDate:i79date_(v[r][x.date]),orderNo:no,purchase:amt,payment:x.payment>=0?i79t_(v[r][x.payment]):'',status:st,company:x.company>=0?i79t_(v[r][x.company]):'',cardName:x.name>=0?i79t_(v[r][x.name]):'',end4:x.end4>=0?i79t_(d[r][x.end4]):'',approvalDate:x.adate>=0?i79date_(v[r][x.adate]):'',approvalNo:x.approval>=0?i79t_(d[r][x.approval]):'',approvalAmount:x.aamount>=0?i79n_(v[r][x.aamount]):0,merchant:x.merchant>=0?i79t_(v[r][x.merchant]):'',source:x.source>=0?i79t_(v[r][x.source]):''});}return{rows:rows,stats:stats,purchase:Math.round(p)};}
function i79feeIx_(h){var aliases=['국제운송료','국제운송비','국제배송료','국제배송비','해외운송료','해외운송비','해외배송료','해외배송비'];var x=i79ix_(h,aliases);if(x>=0)return x;for(var i=0;i<h.length;i++){var c=i79c_(h[i]);if((c.indexOf('국제')>=0||c.indexOf('해외')>=0)&&(c.indexOf('운송')>=0||c.indexOf('배송')>=0))return i;}return -1;}
function i79readHist_(sh){var v=sh.getDataRange().getValues(),d=sh.getDataRange().getDisplayValues(),hr=i79header_(v,['카드사','승인금액']);if(hr<0)hr=0;var h=v[hr],x={company:i79ix_(h,['카드사']),name:i79ix_(h,['카드명']),number:i79ix_(h,['카드번호']),end4:i79ix_(h,['카드번호끝4']),date:i79ix_(h,['승인일','이용일','거래일']),merchant:i79ix_(h,['가맹점명','이용가맹점']),amount:i79ix_(h,['승인금액','이용금액','거래금액']),approval:i79ix_(h,['승인번호']),status:i79ix_(h,['승인상태','승인/취소구분','상태']),cancelAmount:i79ix_(h,['취소금액']),evidence:i79ix_(h,['증빙유형']),lotte:i79ix_(h,['롯데계열여부']),source:i79ix_(h,['원본파일'])},a=[];for(var r=hr+1;r<v.length;r++){var date=x.date>=0?i79date_(v[r][x.date]):'',amt=x.amount>=0?i79n_(v[r][x.amount]):0;if(!date&&!amt)continue;var q={row:r+1,company:x.company>=0?i79t_(v[r][x.company]):'',cardName:x.name>=0?i79t_(v[r][x.name]):'',cardNumber:x.number>=0?i79t_(d[r][x.number]):'',end4:x.end4>=0?i79t_(d[r][x.end4]):'',date:date,merchant:x.merchant>=0?i79t_(v[r][x.merchant]):'',amount:amt,approvalNo:x.approval>=0?i79t_(d[r][x.approval]):'',status:x.status>=0?i79t_(v[r][x.status]):'',cancelAmount:x.cancelAmount>=0?i79n_(v[r][x.cancelAmount]):0,evidence:x.evidence>=0?i79t_(v[r][x.evidence]):'',lotte:x.lotte>=0?i79t_(v[r][x.lotte]):'',source:x.source>=0?i79t_(v[r][x.source]):''};q.nonCard=/비카드|현금영수증|페이머니|머니/.test(i79c_([q.company,q.cardName,q.evidence].join(' ')));q.cancel=i79cancelRow_(q);q.lotteEvidence=i79t_(q.lotte).toUpperCase()==='Y'||/롯데|LOTTE/i.test(q.merchant);a.push(q);}return a;}
function i79canon_(raw){var g={},out=[];raw.forEach(function(q){var app=i79c_(q.approvalNo),co=i79c_(q.company);if(!q.nonCard&&app&&co){var k='APP|'+co+'|'+app;if(!g[k])g[k]=[];g[k].push(q);}else{var s=i79single_(q);if(s)out.push(s);}});Object.keys(g).forEach(function(k){var a=g[k],pos=a.filter(function(q){return q.amount>0;});if(!pos.length)return;var rep=pos[0],orig=0,cancel=0;a.forEach(function(q){if(q.amount>orig)orig=q.amount;var c=Math.abs(q.cancelAmount||0);if(q.amount<0)c=Math.max(c,Math.abs(q.amount));if(q.cancel&&q.amount>0)c=Math.max(c,q.amount);if(c>cancel)cancel=c;});cancel=Math.min(cancel,orig);out.push(i79co_(rep,Math.max(orig-cancel,0),orig,orig>0&&orig-cancel===0,k));});return out;}
function i79single_(q){if(q.cancel&&q.amount<0)return null;var orig=Math.abs(q.amount||0),cancel=Math.abs(q.cancelAmount||0);if(q.cancel&&orig>0)cancel=Math.max(cancel,orig);return i79co_(q,Math.max(orig-cancel,0),orig,orig>0&&orig-cancel===0,'ROW|'+q.row);}
function i79co_(q,amt,orig,full,k){return{company:q.company,cardName:q.cardName,end4:q.end4,date:q.date,merchant:q.merchant,amount:amt,originalAmount:orig,approvalNo:q.approvalNo,source:q.source,nonCard:q.nonCard,lotteEvidence:q.lotteEvidence,fullyCanceled:full,key:q.approvalNo?'APP|'+i79c_(q.company)+'|'+i79c_(q.approvalNo):'ROW|'+q.date+'|'+amt+'|'+i79c_(q.merchant)+'|'+i79c_(q.source),canonKey:k};}
function i79used_(rows){var u={};rows.forEach(function(o){if(o.status!=='MATCHED'&&o.status!=='NON_CARD')return;var k=o.approvalNo?'APP|'+i79c_(o.company)+'|'+i79c_(o.approvalNo):(o.approvalDate||o.approvalAmount||o.merchant||o.source?'ROW|'+o.approvalDate+'|'+o.approvalAmount+'|'+i79c_(o.merchant)+'|'+i79c_(o.source):'');if(k)u[k]=(u[k]||0)+1;});return u;}
function i79writeV2_(ss,rows){var sh=ss.getSheetByName(I79D)||ss.insertSheet(I79D);if(sh.getFilter())sh.getFilter().remove();sh.clear();var h=['사업자등록번호','쿠팡계정ID','주문일','주문번호','기존주문매입금액','롯데결제수단','현재주문상태','상태컬럼근거','반품취소완료','국제운송료후보','재매칭기준','재매칭목표금액','검색창','PREVIEW판정','정확후보수','후보승인일','후보카드사','후보카드명','후보끝4','후보승인번호','후보금액','후보가맹점','후보원본','후보요약'];sh.getRange(1,1,1,h.length).setValues([h]);if(rows.length)sh.getRange(2,1,rows.length,h.length).setValues(rows);sh.setFrozenRows(1);sh.getRange(1,1,1,h.length).setFontWeight('bold');if(rows.length){sh.getRange(2,4,rows.length,1).setNumberFormat('@');sh.getRange(2,5,rows.length,1).setNumberFormat('#,##0');sh.getRange(2,10,rows.length,1).setNumberFormat('@');sh.getRange(2,12,rows.length,1).setNumberFormat('#,##0');sh.getRange(2,19,rows.length,2).setNumberFormat('@');sh.getRange(2,21,rows.length,1).setNumberFormat('#,##0');}try{sh.getRange(1,1,rows.length+1,h.length).createFilter();}catch(_e){}}
function i79status_(ss,p){var sh=ss.getSheetByName(I79S)||ss.insertSheet(I79S);sh.clearContents();sh.getRange(1,1,1,2).setValues([['항목','값']]);if(p.length)sh.getRange(2,1,p.length,2).setValues(p);sh.setFrozenRows(1);sh.getRange(1,1,1,2).setFontWeight('bold');sh.autoResizeColumns(1,2);}
function i79summary_(a){return a.slice(0,6).map(function(q){return[q.date,q.amount,q.company,q.cardName,q.end4,q.approvalNo,q.merchant].join('|');}).join(' / ');}
function i79distinctAbs_(a){var m={},o=[];(a||[]).forEach(function(x){var n=Math.abs(Math.round(Number(x)||0));if(n&&!m[n]){m[n]=1;o.push(n);}});return o.sort(function(a,b){return a-b;});}
function i79cancelLike_(s){return /취소|반품|환불|cancel|return|refund/i.test(s||'');}
function i79cancelRow_(q){var s=i79c_(q.status);if(q.amount<0)return true;if(!s)return false;if(s.indexOf('취소있음')>=0)return false;return s.indexOf('취소')>=0||s.indexOf('환불')>=0;}
function i79payConflict_(p,c){var a=i79c_(p),b=i79c_(c);if(!a||!b||/lpay|엘페이|토스|카카오/.test(a))return false;var k=[['국민','국민'],['kb','kb'],['우리','우리'],['신한','신한'],['농협','농협'],['nh','nh'],['삼성','삼성'],['하나','하나'],['현대','현대'],['롯데','롯데']];for(var i=0;i<k.length;i++)if(a.indexOf(k[i][0])>=0)return b.indexOf(k[i][1])<0;return false;}
function i79days_(a,b){if(!a||!b)return 9999;var x=new Date(a+'T00:00:00'),y=new Date(b+'T00:00:00');return Math.round((y.getTime()-x.getTime())/86400000);}
function i79header_(v,req){for(var r=0;r<Math.min(v.length,30);r++){var h=v[r]||[],ok=req.every(function(n){return i79ix_(h,[n])>=0;});if(ok)return r;}return -1;}
function i79ix_(h,n){var m={};(h||[]).forEach(function(v,i){m[i79c_(v)]=i;});for(var j=0;j<n.length;j++){var k=i79c_(n[j]);if(Object.prototype.hasOwnProperty.call(m,k))return m[k];}return -1;}
function i79t_(v){if(v===null||v===undefined)return '';if(Object.prototype.toString.call(v)==='[object Date]')return Utilities.formatDate(v,Session.getScriptTimeZone()||'Asia/Seoul','yyyy-MM-dd');return String(v).trim();}
function i79c_(v){return i79t_(v).toLowerCase().replace(/[\s_\-\/.()\[\]:]+/g,'');}
function i79n_(v){if(typeof v==='number'&&isFinite(v))return Math.round(v);var s=String(v===null||v===undefined?'':v).replace(/[^0-9.\-]/g,'');return s?Math.round(Number(s)||0):0;}
function i79date_(v){if(Object.prototype.toString.call(v)==='[object Date]')return Utilities.formatDate(v,Session.getScriptTimeZone()||'Asia/Seoul','yyyy-MM-dd');var s=i79t_(v),m=s.match(/(20\d{2})[^0-9]?(\d{1,2})[^0-9]?(\d{1,2})/);if(!m)return s;return m[1]+'-'+('0'+m[2]).slice(-2)+'-'+('0'+m[3]).slice(-2);}
function i79sig_(sh){var v=sh.getDataRange().getValues(),s=JSON.stringify(v,function(k,x){return Object.prototype.toString.call(x)==='[object Date]'?x.toISOString():x;});var b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s,Utilities.Charset.UTF_8);return b.map(function(x){var n=x<0?x+256:x;return('0'+n.toString(16)).slice(-2);}).join('');}
