var LOTTEON_REMOTE_TASK={id:'ISSUE75-v1.2-20260814',title:'v6.74 안전회수 운영반영+기간별 동기화 v1.2',enabled:true,statusSheet:'ISSUE75_실행상태'};
var X75V='v1.2-ISSUE75-V674-GUARDED-PRODUCTION-APPLY-FORMAT-PREFLIGHT';
var X75S='ISSUE75_실행상태',X75C='부가세_카드매칭검증',X75P='부가세_기간별',X75VAT='부가세_신고자료',X75PV='ISSUE74_카드회수PREVIEW';
var X75BS='ISSUE75_사업자별부가세PREVIEW',X75CB='ISSUE75_백업_부가세카드매칭검증',X75PB='ISSUE75_백업_부가세기간별';
var X75PRO=['매출데이터_붙여넣기','부가세_신고자료','카드사용내역_붙여넣기','카드_마스터','ISSUE73_NOMATCH회수진단','ISSUE73_실행상태','ISSUE74_카드회수PREVIEW','ISSUE74_회수변경내역','ISSUE74_실행상태'];
function runLotteonRemoteTaskStartRemote_(){return x75run_();}
function runLotteonRemoteTaskContinueRemote_(){return x75run_();}

function x75run_(){
 var ss=SpreadsheetApp.getActive(),before={},card=null,period=null,cb=null,pb=null,cf=null,pf=null,cardW=false,periodW=false,changed=[],oldFR=0,oldFC=0,oldWidths=[];
 try{
  x75status_(ss,[['version',X75V],['상태','RUNNING'],['단계','GUARD'],['메시지','Issue75 v1.1 rollback 후 format-before-values preflight 및 guarded 재반영 중']]);
  [X75C,X75P,X75VAT,X75PV,'ISSUE74_실행상태'].forEach(function(n){if(!ss.getSheetByName(n))throw new Error('필수 시트 누락: '+n);});
  X75PRO.forEach(function(n){var sh=ss.getSheetByName(n);if(!sh)throw new Error('보호 시트 누락: '+n);before[n]=x75sig_(sh);});
  x75guard74_(ss);
  card=ss.getSheetByName(X75C);period=ss.getSheetByName(X75P);
  if(x75formulaCount_(card))throw new Error('부가세_카드매칭검증 formula 존재');
  if(x75formulaCount_(period))throw new Error('부가세_기간별 formula 존재');
  var old=x75card_(card),pv=x75card_(ss.getSheetByName(X75PV));
  x75guardOld_(old);x75guardFinal_(pv);
  var cd=x75cardDiff_(old,pv);if(cd.changed!==27||cd.bad!==0||cd.date!==26||cd.split!==1||cd.protected!==0)throw new Error('Issue74 preview 변경집합 guard 실패 '+JSON.stringify(cd));changed=cd.rows.slice();

  var vat=x75vatOrders_(ss.getSheetByName(X75VAT));var attach=x75attach_(vat,pv);if(attach.overlap!==1355||attach.vatOnly||attach.cardOnly||attach.purchaseMismatch||attach.businessMismatch)throw new Error('VAT×preview 1:1 실패 '+JSON.stringify(attach));
  var summary=x75summary_(vat),sst=x75summaryStats_(summary);x75guardSummary_(sst);
  var previewSheet=x75writeBusinessPreview_(ss,summary);

  var pd=x75period_(period),pst=x75guardPeriod_(pd);
  var pre=x75makePreflight_(ss,period,pd,summary,previewSheet);
  if(pre.typed||pre.display)throw new Error('format-before-values preflight 불일치 '+JSON.stringify(pre));

  cf=x75capFilter_(card);pf=x75capFilter_(period);oldFR=period.getFrozenRows();oldFC=period.getFrozenColumns();for(var wi=1;wi<=Math.min(24,period.getMaxColumns());wi++)oldWidths.push(period.getColumnWidth(wi));
  cb=x75backup_(ss,card,X75CB);pb=x75backup_(ss,period,X75PB);
  var cbd=x75sheetDiff_(card,cb),pbd=x75sheetDiff_(period,pb);if(cbd.typed||cbd.display||pbd.typed||pbd.display)throw new Error('backup exact 실패');

  x75removeFilter_(card);cardW=true;
  changed.forEach(function(r){card.getRange(r+1,1,1,pv.values[r].length).setValues([pv.values[r]]);});
  x75restoreFilter_(card,cf,null);SpreadsheetApp.flush();
  var now=x75card_(card);x75guardFinal_(now);var cm=x75matrixDiff_(pv.values,card.getDataRange().getValues());var cmd=x75matrixDiff_(ss.getSheetByName(X75PV).getDataRange().getDisplayValues(),card.getDataRange().getDisplayValues());if(cm||cmd)throw new Error('운영카드/Issue74 preview 불일치 typed='+cm+' display='+cmd);

  var start=summary.length+5;
  x75removeFilter_(period);periodW=true;period.clearContents();x75grid_(period,start+pd.values.length+2,24);
  if(summary.length){period.getRange(3,1,summary.length,11).setNumberFormat('@');for(var nc=12;nc<=23;nc++)period.getRange(3,nc,summary.length,1).setNumberFormat('#,##0');}
  if(pd.values.length)period.getRange(start,1,pd.values.length,pd.width).setNumberFormats(pd.formats);
  period.getRange(1,1).setValue('사업자별 반기 신고요약 (구매카드별)');
  var hh=x75summaryHeaders_();period.getRange(2,1,1,24).setValues([hh]);if(summary.length)period.getRange(3,1,summary.length,24).setValues(summary);if(pd.values.length)period.getRange(start,1,pd.values.length,pd.width).setValues(pd.values);
  period.getRange(1,1,1,24).setBackground('#b4c6e7').setFontWeight('bold');period.getRange(2,1,1,24).setBackground('#d9eaf7').setFontWeight('bold').setHorizontalAlignment('center');if(pd.values.length)period.getRange(start,1,1,pd.width).setBackground('#d9eaf7').setFontWeight('bold').setHorizontalAlignment('center');
  x75widths_(period,hh,pd.headers);period.setFrozenRows(2);x75restoreFilter_(period,pf,{from:pd.headerRow,to:start});SpreadsheetApp.flush();

  var topTyped=x75matrixDiff_(previewSheet.getDataRange().getValues(),period.getRange(2,1,summary.length+1,24).getValues());
  var topDisplay=x75matrixDiff_(previewSheet.getDataRange().getDisplayValues(),period.getRange(2,1,summary.length+1,24).getDisplayValues());
  if(topTyped||topDisplay)throw new Error('기간별 상단요약 불일치 typed='+topTyped+' display='+topDisplay+' detail='+x75diffDetail_(previewSheet.getDataRange(),period.getRange(2,1,summary.length+1,24)));
  var dr=period.getRange(start,1,pd.values.length,pd.width),dt=x75matrixDiff_(pd.values,dr.getValues()),dd=x75matrixDiff_(pd.display,dr.getDisplayValues());if(dt||dd)throw new Error('기간별 하단집계 보존 실패 typed='+dt+' display='+dd);
  var pda=x75period_(period),psta=x75guardPeriod_(pda);if(psta.halfRows!==pst.halfRows||psta.monthRows!==pst.monthRows||psta.unknown!==0)throw new Error('기간집계 구조 변화');
  var top=x75topStats_(period,pda.headerRow);if(!x75topOk_(top))throw new Error('기간별 상단 집계 guard 실패 '+JSON.stringify(top));
  var cv=x75verifyFilter_(card,cf,null),pvf=x75verifyFilter_(period,pf,{from:pd.headerRow,to:start});if(!cv.ok||!pvf.ok)throw new Error('filter 복원 실패 card='+JSON.stringify(cv)+' period='+JSON.stringify(pvf));
  x75protect_(ss,before);

  x75status_(ss,[['version',X75V],['상태','PASS'],['단계','DONE'],['메시지','v6.74 안전회수 27건 운영반영 및 부가세_기간별 동기화 완료'],['운영주문',1355],['v6.74_DATE_RECOVERED',26],['v6.74_DATE_RECOVERED_매입',1847530],['v6.74_SPLIT_RECOVERED',1],['v6.74_SPLIT_RECOVERED_매입',11720],['v6.74_총회수',27],['v6.74_회수매입합계',1859250],['MATCHED',835],['NON_CARD',498],['AMBIGUOUS',0],['NO_MATCH',22],['매입합계',105762969],['사업자×카드요약행',summary.length],['순수매출액',138432300],['정산기준금액',122495855],['마켓수수료',15936445],['매출부가세',12584695],['매입부가세',9614786],['납부예상부가세',2969909],['예상이익',16732886],['부가세반영예상이익',13762977],['기간집계행',pda.values.length-1],['반기집계행',psta.halfRows],['월별집계행',psta.monthRows],['기간미확인',psta.unknown],['FORMAT_BEFORE_VALUES_PREFLIGHT_typed',pre.typed],['FORMAT_BEFORE_VALUES_PREFLIGHT_display',pre.display],['운영요약/preview_typed차이',topTyped],['운영요약/preview_display차이',topDisplay],['기간상세_typed차이',dt],['기간상세_display차이',dd],['카드백업_typed차이',cbd.typed],['카드백업_display차이',cbd.display],['기간백업_typed차이',pbd.typed],['기간백업_display차이',pbd.display],['카드기존filter복원',cf.exists?'YES':'NO'],['카드기존filterCriteria수',cf.criteria.length],['기간기존filter복원',pf.exists?'YES':'NO'],['기간기존filterCriteria수',pf.criteria.length],['보호시트변경수',0],['롤백',0],['오류',''],['완료시각',new Date().toISOString()]]);
  try{ss.toast('Issue75 v1.2 PASS: MATCHED 835 / NO_MATCH 22 / 기간별 동기화 완료','LOTTEON',10);}catch(_e){}
  return{ok:true,done:true,version:X75V,matched:835,noMatch:22,recovered:27};
 }catch(e){
  var msg=String(e&&e.message?e.message:e);
  if(cardW||periodW){try{
    if(cardW&&card&&cb){x75removeFilter_(card);var bv=cb.getDataRange().getValues();changed.forEach(function(r){card.getRange(r+1,1,1,bv[r].length).setValues([bv[r]]);});x75restoreFilter_(card,cf,null);}
    if(periodW&&period&&pb){x75removeFilter_(period);period.clear();var br=pb.getDataRange();x75grid_(period,br.getNumRows()+2,br.getNumColumns());br.copyTo(period.getRange(1,1,br.getNumRows(),br.getNumColumns()),SpreadsheetApp.CopyPasteType.PASTE_NORMAL,false);period.setFrozenRows(oldFR);period.setFrozenColumns(oldFC);for(var j=0;j<oldWidths.length;j++)period.setColumnWidth(j+1,oldWidths[j]);x75restoreFilter_(period,pf,null);}
    SpreadsheetApp.flush();var cdr=cardW?x75sheetDiff_(card,cb):{typed:0,display:0},pdr=periodW?x75sheetDiff_(period,pb):{typed:0,display:0};if(cdr.typed||cdr.display||pdr.typed||pdr.display)throw new Error('rollback exact 실패 card='+JSON.stringify(cdr)+' period='+JSON.stringify(pdr));
    x75status_(ss,[['version',X75V],['상태','ROLLED_BACK'],['단계','FAILED'],['메시지','운영 반영 중 오류, 기존 카드/기간별 복구 완료'],['롤백',1],['오류',msg],['완료시각',new Date().toISOString()]]);
   }catch(re){x75status_(ss,[['version',X75V],['상태','ROLLBACK_ERROR'],['단계','FAILED'],['메시지','운영 반영 및 자동복구 실패'],['롤백',-1],['오류',msg+' / rollback: '+String(re&&re.message?re.message:re)],['완료시각',new Date().toISOString()]]);}
  }else{x75status_(ss,[['version',X75V],['상태','ERROR'],['단계','FAILED'],['메시지','운영 write 전 guard/preflight 실패'],['롤백',0],['오류',msg],['완료시각',new Date().toISOString()]]);}
  throw e;
 }
}

function x75guard74_(ss){var v=ss.getSheetByName('ISSUE74_실행상태').getDataRange().getValues(),m={};for(var i=1;i<v.length;i++)m[x75t_(v[i][0])]=v[i][1];var q={'상태':'PASS','단계':'DONE','운영주문':1355,'운영_MATCHED':808,'운영_NON_CARD':498,'운영_AMBIGUOUS':0,'운영_NO_MATCH':49,'PREVIEW_DATE_RECOVERED':26,'PREVIEW_SPLIT_RECOVERED':1,'PREVIEW_총회수':27,'PREVIEW_MATCHED':835,'PREVIEW_NON_CARD':498,'PREVIEW_AMBIGUOUS':0,'PREVIEW_NO_MATCH':22,'PREVIEW_매입합계':105762969,'AUTO_SAFE외변경행':0,'기존_MATCHED_NONCARD_변경행':0,'보호시트변경수':0};Object.keys(q).forEach(function(k){if(typeof q[k]==='number'){if(Number(m[k])!==q[k])throw new Error('Issue74 guard '+k+'='+m[k]);}else if(x75t_(m[k])!==q[k])throw new Error('Issue74 guard '+k+'='+m[k]);});}
function x75card_(sh){var v=sh.getDataRange().getValues(),hr=x75header_(v,['주문번호','카드매칭상태']),h=v[hr],x={year:x75ix_(h,['신고연도']),half:x75ix_(h,['반기']),date:x75ix_(h,['주문일']),business:x75ix_(h,['사업자등록번호']),account:x75ix_(h,['쿠팡계정ID']),order:x75ix_(h,['주문번호']),purchase:x75ix_(h,['주문매입금액']),company:x75ix_(h,['구매카드사']),alias:x75ix_(h,['구매카드별칭']),name:x75ix_(h,['구매카드명']),number:x75ix_(h,['카드번호']),end4:x75ix_(h,['카드번호끝4']),status:x75ix_(h,['카드매칭상태']),reason:x75ix_(h,['카드매칭근거'])},stats={MATCHED:0,NON_CARD:0,AMBIGUOUS:0,NO_MATCH:0},rows=[],purchase=0,keys={};for(var r=hr+1;r<v.length;r++){var no=x75t_(v[r][x.order]);if(!no)continue;var key=x75c_(v[r][x.account])+'|'+x75c_(no);if(keys[key])throw new Error('card key 중복 '+key);keys[key]=1;var s=x75t_(v[r][x.status]).toUpperCase(),p=x75n_(v[r][x.purchase]);stats[s]=(stats[s]||0)+1;purchase+=p;rows.push({r:r,key:key,status:s,purchase:p});}return{values:v,hr:hr,h:h,x:x,stats:stats,rows:rows,purchase:purchase};}
function x75guardOld_(a){if(a.rows.length!==1355||a.stats.MATCHED!==808||a.stats.NON_CARD!==498||a.stats.AMBIGUOUS!==0||a.stats.NO_MATCH!==49||a.purchase!==105762969)throw new Error('운영카드 rollback 상태 guard 실패 '+JSON.stringify(a.stats)+' purchase='+a.purchase);}
function x75guardFinal_(a){if(a.rows.length!==1355||a.stats.MATCHED!==835||a.stats.NON_CARD!==498||a.stats.AMBIGUOUS!==0||a.stats.NO_MATCH!==22||a.purchase!==105762969)throw new Error('final 카드 guard 실패 '+JSON.stringify(a.stats)+' purchase='+a.purchase);}
function x75cardDiff_(a,b){var m={},rows=[],bad=0,date=0,split=0,prot=0;for(var r=a.hr+1;r<a.values.length;r++){var no=x75t_(a.values[r][a.x.order]);if(no)m[x75c_(a.values[r][a.x.account])+'|'+x75c_(no)]={r:r,row:a.values[r]};}for(var s=b.hr+1;s<b.values.length;s++){var no2=x75t_(b.values[s][b.x.order]);if(!no2)continue;var k=x75c_(b.values[s][b.x.account])+'|'+x75c_(no2),o=m[k];if(!o)throw new Error('preview extra key '+k);if(x75roweq_(o.row,b.values[s]))continue;rows.push(o.r);var os=x75t_(o.row[a.x.status]).toUpperCase(),ns=x75t_(b.values[s][b.x.status]).toUpperCase(),reason=x75t_(b.values[s][b.x.reason]);if(os==='MATCHED'||os==='NON_CARD')prot++;if(os!=='NO_MATCH'||ns!=='MATCHED')bad++;if(reason==='v6.74_-1일_exact_단일미사용증빙_1:1회수')date++;else if(reason==='v6.74_split_exact_동일카드_2증빙_1:1회수')split++;else bad++;}return{changed:rows.length,bad:bad,date:date,split:split,protected:prot,rows:rows};}
function x75vatOrders_(sh){var v=sh.getDataRange().getValues(),h=v[0],ix=function(a){return x75ix_(h,a);},x={year:ix(['신고연도']),half:ix(['반기']),business:ix(['사업자등록번호']),account:ix(['쿠팡계정ID']),order:ix(['주문번호','마켓주문번호']),sales:ix(['순수매출액']),ss:ix(['매출공급가액']),sv:ix(['매출부가세']),settle:ix(['정산기준금액']),fee:ix(['마켓수수료/비용','마켓수수료']),purchase:ix(['매입금액']),ps:ix(['매입공급가액']),pv:ix(['매입부가세']),pay:ix(['납부예상부가세']),profit:ix(['예상이익']),vp:ix(['부가세반영예상이익'])};Object.keys(x).forEach(function(k){if(x[k]<0&&k!=='fee')throw new Error('VAT header '+k);});var m={};for(var r=1;r<v.length;r++){var z=v[r],year=x75t_(z[x.year]),half=x75t_(z[x.half]);if(year!=='2026'||half!=='상반기')continue;var biz=x75t_(z[x.business]),acc=x75t_(z[x.account]),no=x75t_(z[x.order]);if(!no)continue;var k=[year,half,biz,acc,no].join('|');if(!m[k])m[k]={key:k,year:year,half:half,business:biz,account:acc,orderNo:no,sales:0,ss:0,sv:0,settle:0,fee:0,purchase:0,ps:0,pv:0,pay:0,profit:0,vp:0};var o=m[k];o.sales+=x75n_(z[x.sales]);o.ss+=x75n_(z[x.ss]);o.sv+=x75n_(z[x.sv]);o.settle+=x75n_(z[x.settle]);o.fee+=x.fee>=0?x75n_(z[x.fee]):x75n_(z[x.sales])-x75n_(z[x.settle]);o.purchase+=x75n_(z[x.purchase]);o.ps+=x75n_(z[x.ps]);o.pv+=x75n_(z[x.pv]);o.pay+=x75n_(z[x.pay]);o.profit+=x75n_(z[x.profit]);o.vp+=x75n_(z[x.vp]);}var a=Object.keys(m).map(function(k){return m[k];});if(a.length!==1355)throw new Error('VAT order count '+a.length);return a;}
function x75attach_(vat,card){var cm={},seen={},x={overlap:0,vatOnly:0,cardOnly:0,purchaseMismatch:0,businessMismatch:0};for(var r=card.hr+1;r<card.values.length;r++){var z=card.values[r],no=x75t_(z[card.x.order]);if(!no)continue;var k=[x75t_(z[card.x.year]),x75t_(z[card.x.half]),x75t_(z[card.x.business]),x75t_(z[card.x.account]),no].join('|');cm[k]={business:x75t_(z[card.x.business]),purchase:x75n_(z[card.x.purchase]),company:x75t_(z[card.x.company]),alias:x75t_(z[card.x.alias]),name:x75t_(z[card.x.name]),number:x75t_(z[card.x.number]),end4:x75t_(z[card.x.end4]),status:x75t_(z[card.x.status]).toUpperCase(),reason:x75t_(z[card.x.reason])};}vat.forEach(function(o){var c=cm[o.key];if(!c){x.vatOnly++;return;}x.overlap++;seen[o.key]=1;if(c.purchase!==o.purchase)x.purchaseMismatch++;if(c.business!==o.business)x.businessMismatch++;o.card=c;});Object.keys(cm).forEach(function(k){if(!seen[k])x.cardOnly++;});return x;}
function x75summary_(a){var m={};a.forEach(function(o){var c=o.card,id=(c.status==='AMBIGUOUS'||c.status==='NO_MATCH')?c.status:[c.company,c.alias,c.name,c.number,c.end4,c.status].join('|'),k=[o.year,o.half,o.business,id].join('|');if(!m[k])m[k]={year:o.year,half:o.half,biz:o.business,acc:{},company:c.company,alias:c.alias,name:c.name,number:c.number,end4:c.end4,status:c.status,reasons:{},orders:{},sales:0,ss:0,sv:0,settle:0,fee:0,purchase:0,ps:0,pv:0,pay:0,profit:0,vp:0};var q=m[k];q.acc[o.account]=1;q.orders[o.orderNo]=1;if(c.reason)q.reasons[c.reason]=1;q.sales+=o.sales;q.ss+=o.ss;q.sv+=o.sv;q.settle+=o.settle;q.fee+=o.fee;q.purchase+=o.purchase;q.ps+=o.ps;q.pv+=o.pv;q.pay+=o.pay;q.profit+=o.profit;q.vp+=o.vp;});return Object.keys(m).map(function(k){var q=m[k];return[q.year,q.half,q.biz,Object.keys(q.acc).sort().join(', '),q.company,q.alias,q.name,q.number,q.end4,q.status,Object.keys(q.reasons).sort().join(' / '),Object.keys(q.orders).length,q.sales,q.ss,q.sv,q.settle,q.fee,q.purchase,q.ps,q.pv,q.pay,q.profit,q.vp,(q.status==='NO_MATCH'||q.status==='AMBIGUOUS')?'카드 미확정':''];}).sort(function(a,b){return String(a[0]).localeCompare(String(b[0]))||String(a[1]).localeCompare(String(b[1]))||String(a[2]).localeCompare(String(b[2]))||String(a[4]).localeCompare(String(b[4]))||String(a[7]).localeCompare(String(b[7]));});}
function x75summaryStats_(a){var t={orders:0,MATCHED:0,NON_CARD:0,AMBIGUOUS:0,NO_MATCH:0,sales:0,settle:0,fee:0,purchase:0,sv:0,pv:0,pay:0,profit:0,vp:0};a.forEach(function(r){var n=x75n_(r[11]),s=x75t_(r[9]).toUpperCase();t.orders+=n;t[s]=(t[s]||0)+n;t.sales+=x75n_(r[12]);t.sv+=x75n_(r[14]);t.settle+=x75n_(r[15]);t.fee+=x75n_(r[16]);t.purchase+=x75n_(r[17]);t.pv+=x75n_(r[19]);t.pay+=x75n_(r[20]);t.profit+=x75n_(r[21]);t.vp+=x75n_(r[22]);});return t;}
function x75guardSummary_(t){if(t.orders!==1355||t.MATCHED!==835||t.NON_CARD!==498||t.AMBIGUOUS!==0||t.NO_MATCH!==22||t.sales!==138432300||t.settle!==122495855||t.fee!==15936445||t.purchase!==105762969||t.sv!==12584695||t.pv!==9614786||t.pay!==2969909||t.profit!==16732886||t.vp!==13762977)throw new Error('summary guard '+JSON.stringify(t));}
function x75summaryHeaders_(){return['신고연도','반기','사업자등록번호','연결 쿠팡계정ID','구매카드사','구매카드별칭','구매카드명','카드번호','카드번호끝4','카드매칭상태','카드매칭근거','주문건수','순수매출액','매출공급가액','매출부가세','정산기준금액','마켓수수료','매입금액','매입공급가액','매입부가세','납부예상부가세','예상이익','부가세반영예상이익','비고'];}
function x75writeBusinessPreview_(ss,a){var sh=ss.getSheetByName(X75BS)||ss.insertSheet(X75BS),h=x75summaryHeaders_();x75removeFilter_(sh);sh.clear();x75grid_(sh,a.length+2,24);if(a.length){sh.getRange(2,1,a.length,11).setNumberFormat('@');for(var c=12;c<=23;c++)sh.getRange(2,c,a.length,1).setNumberFormat('#,##0');}sh.getRange(1,1,1,24).setValues([h]);if(a.length)sh.getRange(2,1,a.length,24).setValues(a);sh.getRange(1,1,1,24).setBackground('#d9eaf7').setFontWeight('bold');return sh;}
function x75period_(sh){var rg=sh.getDataRange(),v=rg.getValues(),d=rg.getDisplayValues(),hr=-1;for(var r=0;r<Math.min(100,v.length);r++)if(x75ix_(v[r],['집계구분'])>=0&&x75ix_(v[r],['신고연도'])>=0){hr=r;break;}if(hr<0)throw new Error('기간집계 header 없음');var w=0;for(var c=0;c<v[hr].length;c++)if(x75t_(v[hr][c]))w=c+1;if(w<16)throw new Error('기간 width '+w);return{headerRow:hr+1,headers:v[hr].slice(0,w),width:w,values:v.slice(hr).map(function(z){return z.slice(0,w);}),display:d.slice(hr).map(function(z){return z.slice(0,w);}),formats:sh.getRange(hr+1,1,v.length-hr,w).getNumberFormats()};}
function x75guardPeriod_(p){var h=p.headers,ix=function(n){return x75ix_(h,[n]);},x={kind:ix('집계구분'),year:ix('신고연도'),half:ix('반기'),orders:ix('주문건수'),sales:ix('순수매출액'),settle:ix('정산기준금액'),fee:ix('마켓수수료'),purchase:ix('매입금액'),sv:ix('매출부가세'),pv:ix('매입부가세'),pay:ix('납부예상부가세'),profit:ix('예상이익'),vp:ix('부가세반영예상이익')};Object.keys(x).forEach(function(k){if(x[k]<0)throw new Error('period header '+k);});var H={rows:0,orders:0,sales:0,settle:0,fee:0,purchase:0,sv:0,pv:0,pay:0,profit:0,vp:0},M={rows:0,orders:0,sales:0,settle:0,fee:0,purchase:0,sv:0,pv:0,pay:0,profit:0,vp:0},u=0;for(var r=1;r<p.values.length;r++){var z=p.values[r],kind=x75t_(z[x.kind]);if(kind==='기간미확인')u++;if(x75t_(z[x.year])!=='2026'||x75t_(z[x.half])!=='상반기')continue;var t=kind==='반기'?H:(kind==='월별'?M:null);if(!t)continue;t.rows++;['orders','sales','settle','fee','purchase','sv','pv','pay','profit','vp'].forEach(function(k){t[k]+=x75n_(z[x[k]]);});}function ok(t){return t.orders===1355&&t.sales===138432300&&t.settle===122495855&&t.fee===15936445&&t.purchase===105762969&&t.sv===12584695&&t.pv===9614786&&t.pay===2969909&&t.profit===16732886&&t.vp===13762977;}if(!ok(H)||!ok(M)||u)throw new Error('period totals H='+JSON.stringify(H)+' M='+JSON.stringify(M)+' u='+u);return{halfRows:H.rows,monthRows:M.rows,unknown:u};}
function x75topStats_(sh,ph){var v=sh.getDataRange().getValues(),h=v[1]||[],st=x75ix_(h,['카드매칭상태']),ord=x75ix_(h,['주문건수']),sales=x75ix_(h,['순수매출액']),settle=x75ix_(h,['정산기준금액']),fee=x75ix_(h,['마켓수수료']),purchase=x75ix_(h,['매입금액']),sv=x75ix_(h,['매출부가세']),pv=x75ix_(h,['매입부가세']),pay=x75ix_(h,['납부예상부가세']),profit=x75ix_(h,['예상이익']),vp=x75ix_(h,['부가세반영예상이익']),t={rows:0,orders:0,MATCHED:0,NON_CARD:0,AMBIGUOUS:0,NO_MATCH:0,sales:0,settle:0,fee:0,purchase:0,sv:0,pv:0,pay:0,profit:0,vp:0};for(var r=2;r<ph-3&&r<v.length;r++){var s=x75t_(v[r][st]).toUpperCase();if(!s)continue;var n=x75n_(v[r][ord]);t.rows++;t.orders+=n;t[s]=(t[s]||0)+n;t.sales+=x75n_(v[r][sales]);t.settle+=x75n_(v[r][settle]);t.fee+=x75n_(v[r][fee]);t.purchase+=x75n_(v[r][purchase]);t.sv+=x75n_(v[r][sv]);t.pv+=x75n_(v[r][pv]);t.pay+=x75n_(v[r][pay]);t.profit+=x75n_(v[r][profit]);t.vp+=x75n_(v[r][vp]);}return t;}
function x75topOk_(t){return t.orders===1355&&t.MATCHED===835&&t.NON_CARD===498&&t.AMBIGUOUS===0&&t.NO_MATCH===22&&t.sales===138432300&&t.settle===122495855&&t.fee===15936445&&t.purchase===105762969&&t.sv===12584695&&t.pv===9614786&&t.pay===2969909&&t.profit===16732886&&t.vp===13762977;}
function x75makePreflight_(ss,period,pd,summary,preview){var name='ISSUE75_FORMAT_PREFLIGHT',old=ss.getSheetByName(name);if(old)ss.deleteSheet(old);var sh=period.copyTo(ss).setName(name);x75removeFilter_(sh);sh.clearContents();var start=summary.length+5;x75grid_(sh,start+pd.values.length+2,24);if(summary.length){sh.getRange(3,1,summary.length,11).setNumberFormat('@');for(var c=12;c<=23;c++)sh.getRange(3,c,summary.length,1).setNumberFormat('#,##0');}if(pd.values.length)sh.getRange(start,1,pd.values.length,pd.width).setNumberFormats(pd.formats);sh.getRange(1,1).setValue('사업자별 반기 신고요약 (구매카드별)');var h=x75summaryHeaders_();sh.getRange(2,1,1,24).setValues([h]);if(summary.length)sh.getRange(3,1,summary.length,24).setValues(summary);if(pd.values.length)sh.getRange(start,1,pd.values.length,pd.width).setValues(pd.values);SpreadsheetApp.flush();var a=preview.getDataRange(),b=sh.getRange(2,1,summary.length+1,24),res={typed:x75matrixDiff_(a.getValues(),b.getValues()),display:x75matrixDiff_(a.getDisplayValues(),b.getDisplayValues()),detail:x75diffDetail_(a,b)};ss.deleteSheet(sh);return res;}
function x75backup_(ss,src,n){var b=ss.getSheetByName(n);if(b){var d=x75sheetDiff_(src,b);if(d.typed||d.display)throw new Error('기존 backup 불일치 '+n);return b;}b=src.copyTo(ss).setName(n);SpreadsheetApp.flush();var x=x75sheetDiff_(src,b);if(x.typed||x.display)throw new Error('backup 생성 실패 '+n);return b;}
function x75capFilter_(sh){var f=sh.getFilter();if(!f)return{exists:false,criteria:[]};var g=f.getRange(),c=[];for(var i=g.getColumn();i<g.getColumn()+g.getNumColumns();i++){var q=f.getColumnFilterCriteria(i);if(q)c.push({col:i,criteria:q});}return{exists:true,row:g.getRow(),col:g.getColumn(),nr:g.getNumRows(),nc:g.getNumColumns(),criteria:c};}
function x75removeFilter_(sh){try{var f=sh.getFilter();if(f)f.remove();}catch(e){}}
function x75restoreFilter_(sh,a,shift){if(!a||!a.exists)return;var row=a.row;if(shift&&row===shift.from)row=shift.to;var nr=Math.min(a.nr,sh.getMaxRows()-row+1),nc=Math.min(a.nc,sh.getMaxColumns()-a.col+1);var f=sh.getRange(row,a.col,nr,nc).createFilter();a.criteria.forEach(function(q){try{f.setColumnFilterCriteria(q.col,q.criteria);}catch(e){}});}
function x75verifyFilter_(sh,a,shift){var f=sh.getFilter();if(!a||!a.exists)return{ok:!f};if(!f)return{ok:false};var row=a.row;if(shift&&row===shift.from)row=shift.to;var g=f.getRange(),cc=0;for(var c=g.getColumn();c<g.getColumn()+g.getNumColumns();c++)if(f.getColumnFilterCriteria(c))cc++;return{ok:g.getRow()===row&&g.getColumn()===a.col&&g.getNumRows()===Math.min(a.nr,sh.getMaxRows()-row+1)&&g.getNumColumns()===Math.min(a.nc,sh.getMaxColumns()-a.col+1)&&cc===a.criteria.length,criteria:cc};}
function x75sheetDiff_(a,b){return{typed:x75matrixDiff_(a.getDataRange().getValues(),b.getDataRange().getValues()),display:x75matrixDiff_(a.getDataRange().getDisplayValues(),b.getDataRange().getDisplayValues())};}
function x75diffDetail_(a,b){var av=a.getValues(),bv=b.getValues(),ad=a.getDisplayValues(),bd=b.getDisplayValues(),out=[];for(var r=0;r<Math.min(av.length,bv.length);r++)for(var c=0;c<Math.min(av[r].length,bv[r].length);c++){if(x75cell_(av[r][c])!==x75cell_(bv[r][c])||x75cell_(ad[r][c])!==x75cell_(bd[r][c])){out.push('R'+(r+1)+'C'+(c+1)+':'+x75cell_(av[r][c])+'/'+x75cell_(ad[r][c])+' != '+x75cell_(bv[r][c])+'/'+x75cell_(bd[r][c]));if(out.length>=6)return out.join(' || ');}}return out.join(' || ');}
function x75protect_(ss,b){var z=[];X75PRO.forEach(function(n){var s=ss.getSheetByName(n);if(!s||x75sig_(s)!==b[n])z.push(n);});if(z.length)throw new Error('보호시트 변경 '+z.join(','));}
function x75status_(ss,p){var sh=ss.getSheetByName(X75S)||ss.insertSheet(X75S);sh.clearContents();sh.getRange(1,1,1,2).setValues([['항목','값']]);if(p.length)sh.getRange(2,1,p.length,2).setValues(p);sh.setFrozenRows(1);sh.getRange(1,1,1,2).setFontWeight('bold');sh.autoResizeColumns(1,2);}
function x75header_(v,a){for(var r=0;r<Math.min(30,v.length);r++){var ok=true;for(var i=0;i<a.length;i++)if(x75ix_(v[r],[a[i]])<0)ok=false;if(ok)return r;}return-1;}
function x75ix_(h,a){var m={};for(var i=0;i<h.length;i++)m[x75c_(h[i])]=i;for(var j=0;j<a.length;j++){var k=x75c_(a[j]);if(Object.prototype.hasOwnProperty.call(m,k))return m[k];}return-1;}
function x75t_(v){if(v===null||v===undefined)return'';if(Object.prototype.toString.call(v)==='[object Date]')return Utilities.formatDate(v,Session.getScriptTimeZone()||'Asia/Seoul','yyyy-MM-dd');return String(v).trim();}
function x75c_(v){return x75t_(v).toLowerCase().replace(/[\s_\-\/.()\[\]:]+/g,'');}
function x75n_(v){if(typeof v==='number')return isNaN(v)?0:Math.round(v);var n=Number(String(v==null?'0':v).replace(/[원,\s]/g,''));return isNaN(n)?0:Math.round(n);}
function x75cell_(v){if(Object.prototype.toString.call(v)==='[object Date]')return'D:'+v.getTime();return typeof v+':'+String(v==null?'':v);}
function x75roweq_(a,b){if(a.length!==b.length)return false;for(var i=0;i<a.length;i++)if(x75cell_(a[i])!==x75cell_(b[i]))return false;return true;}
function x75matrixDiff_(a,b){if(a.length!==b.length)return 1;var n=0;for(var r=0;r<a.length;r++){if(a[r].length!==b[r].length){n++;continue;}for(var c=0;c<a[r].length;c++)if(x75cell_(a[r][c])!==x75cell_(b[r][c]))n++;}return n;}
function x75sig_(sh){var v=sh.getDataRange().getDisplayValues(),h=2166136261;function add(s){s=String(s);for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}}for(var r=0;r<v.length;r++)for(var c=0;c<v[r].length;c++){add(v[r][c]);add('|');}return String(h>>>0);}
function x75formulaCount_(sh){var f=sh.getDataRange().getFormulas(),n=0;for(var r=0;r<f.length;r++)for(var c=0;c<f[r].length;c++)if(f[r][c])n++;return n;}
function x75grid_(sh,r,c){if(sh.getMaxRows()<r)sh.insertRowsAfter(sh.getMaxRows(),r-sh.getMaxRows());if(sh.getMaxColumns()<c)sh.insertColumnsAfter(sh.getMaxColumns(),c-sh.getMaxColumns());}
function x75widths_(sh,h,d){for(var i=0;i<24;i++){var x=h[i]||d[i]||'';sh.setColumnWidth(i+1,/근거|비고/.test(x)?180:(/카드|사업자|계정/.test(x)?135:(/금액|부가세|이익|수수료/.test(x)?110:90)));}}
