var LOTTEON_REMOTE_TASK={id:'ISSUE73-v1.0-20260814',title:'NO_MATCH 49 회수가능성 정밀진단',enabled:true,statusSheet:'ISSUE73_실행상태'};
var I73_VERSION='v1.0-ISSUE73-NOMATCH-RECOVERY-DEEP-DIAGNOSTIC';
var I73_DETAIL='ISSUE73_NOMATCH회수진단',I73_STATUS='ISSUE73_실행상태';
var I73_CORE=['매출데이터_붙여넣기','부가세_신고자료','부가세_카드매칭검증','부가세_기간별','카드사용내역_붙여넣기','카드_마스터'];
function runLotteonRemoteTaskStartRemote_(){return i73Run_();}
function runLotteonRemoteTaskContinueRemote_(){return i73Run_();}

function i73Run_(){var ss=SpreadsheetApp.getActive(),before={};try{
 i73Status_(ss,[['version',I73_VERSION],['상태','RUNNING'],['단계','GUARD'],['메시지','NO_MATCH 49 정밀진단 준비 중']]);
 I73_CORE.forEach(function(n){var s=ss.getSheetByName(n);if(!s)throw new Error('핵심 시트 누락: '+n);before[n]=i73Sig_(s);});
 i73Guard72_(ss);
 var card=i73ReadCard_(ss.getSheetByName('부가세_카드매칭검증'));i73GuardCard_(card);
 var hist=i73ReadHist_(ss.getSheetByName('카드사용내역_붙여넣기'));
 var used=i73UsedSet_(card.rows),out=[],sum={date38:0,datePurchase:0,dateSafe:0,dateSafePurchase:0,dateUsed:0,dateMulti:0,dateConflict:0,dateNoCandidate:0,amount9:0,amountPurchase:0,splitSafe:0,splitSafePurchase:0,amountNearest:0,zero:0,cancel:0,other:0};var lag={};
 card.rows.filter(function(o){return o.status==='NO_MATCH';}).forEach(function(o){
  var d=i73Diag_(o,hist,used),bucket=d.bucket;
  if(bucket==='DATE_EXACT'){sum.date38++;sum.datePurchase+=o.purchase;lag[String(d.lag)]=(lag[String(d.lag)]||0)+1;if(d.verdict==='AUTO_SAFE_DATE_WINDOW'){sum.dateSafe++;sum.dateSafePurchase+=o.purchase;}else if(d.verdict==='USED_BY_OTHER')sum.dateUsed++;else if(d.verdict==='MULTI_CANDIDATE')sum.dateMulti++;else if(d.verdict==='PAYMENT_CONFLICT')sum.dateConflict++;else if(d.verdict==='NO_CANDIDATE')sum.dateNoCandidate++;}
  else if(bucket==='AMOUNT_DIFF'){sum.amount9++;sum.amountPurchase+=o.purchase;if(d.verdict==='AUTO_SAFE_SPLIT'){sum.splitSafe++;sum.splitSafePurchase+=o.purchase;}else sum.amountNearest++;}
  else if(bucket==='ZERO')sum.zero++;else if(bucket==='CANCELED')sum.cancel++;else sum.other++;
  out.push([o.business,o.account,o.orderDate,o.orderNo,o.purchase,o.payment,o.reason,bucket,d.verdict,d.lag,d.candidateCount,d.unusedCount,d.usedCount,d.identityCount,d.candidateType,d.candidateIdentity,d.candidateDate,d.candidateAmount,d.nearestAmount,d.amountDiff,d.diffRate,d.splitPairCount,d.splitIdentity,d.splitUsed,d.summary]);
 });
 if(out.length!==49)throw new Error('NO_MATCH 행수 불일치: '+out.length);
 if(sum.date38!==38||sum.amount9!==9||sum.zero!==1||sum.cancel!==1)throw new Error('Issue72 원인분포 재현 실패: '+JSON.stringify(sum));
 i73Write_(ss,out);
 var changed=[];I73_CORE.forEach(function(n){var s=ss.getSheetByName(n);if(!s||i73Sig_(s)!==before[n])changed.push(n);});if(changed.length)throw new Error('보호시트 변경 감지: '+changed.join(', '));
 var st=[['version',I73_VERSION],['상태','PASS'],['단계','DONE'],['메시지','NO_MATCH 49 회수가능성 정밀진단 완료'],['NO_MATCH',49],['날짜차이정확금액',sum.date38],['날짜차이_매입합계',sum.datePurchase],['AUTO_SAFE_DATE_WINDOW',sum.dateSafe],['AUTO_SAFE_DATE_WINDOW_매입합계',sum.dateSafePurchase],['DATE_USED_BY_OTHER',sum.dateUsed],['DATE_MULTI_CANDIDATE',sum.dateMulti],['DATE_PAYMENT_CONFLICT',sum.dateConflict],['DATE_NO_CANDIDATE',sum.dateNoCandidate],['기간내금액불일치',sum.amount9],['금액불일치_매입합계',sum.amountPurchase],['AUTO_SAFE_SPLIT',sum.splitSafe],['AUTO_SAFE_SPLIT_매입합계',sum.splitSafePurchase],['AMOUNT_REVIEW',sum.amountNearest],['매입금액0',sum.zero],['완전취소',sum.cancel],['기타',sum.other]];
 Object.keys(lag).sort(function(a,b){return Number(a)-Number(b);}).forEach(function(k){st.push(['DATE_LAG_'+k,lag[k]]);});st.push(['보호시트변경수',0],['오류',''],['완료시각',new Date().toISOString()]);i73Status_(ss,st);return {ok:true,done:true,version:I73_VERSION,dateSafe:sum.dateSafe,splitSafe:sum.splitSafe};
 }catch(e){var m=String(e&&e.message?e.message:e);try{i73Status_(ss,[['version',I73_VERSION],['상태','ERROR'],['단계','FAILED'],['메시지','Issue73 진단 실패'],['오류',m],['완료시각',new Date().toISOString()]]);}catch(_e){}throw e;}}

function i73Guard72_(ss){var s=ss.getSheetByName('ISSUE72_실행상태');if(!s)throw new Error('ISSUE72_실행상태 누락');var v=s.getDataRange().getValues(),m={};for(var r=1;r<v.length;r++)m[i73T_(v[r][0])]=v[r][1];if(i73T_(m['상태'])!=='PASS'||i73T_(m['단계'])!=='DONE'||Number(m['NO_MATCH'])!==49||Number(m['NON_CARD'])!==498||Number(m['보호시트변경수'])!==0)throw new Error('Issue72 PASS exact guard 실패');}
function i73ReadCard_(s){var v=s.getDataRange().getValues(),hr=i73Header_(v,['주문번호','카드매칭상태']),h=v[hr],x={date:i73Ix_(h,['주문일']),business:i73Ix_(h,['사업자등록번호']),account:i73Ix_(h,['쿠팡계정ID']),order:i73Ix_(h,['주문번호']),purchase:i73Ix_(h,['주문매입금액']),payment:i73Ix_(h,['롯데결제수단']),status:i73Ix_(h,['카드매칭상태']),reason:i73Ix_(h,['카드매칭근거']),company:i73Ix_(h,['구매카드사']),name:i73Ix_(h,['구매카드명']),number:i73Ix_(h,['카드번호']),end4:i73Ix_(h,['카드번호끝4']),adate:i73Ix_(h,['승인일']),approval:i73Ix_(h,['승인번호']),aamount:i73Ix_(h,['승인금액']),merchant:i73Ix_(h,['가맹점명']),source:i73Ix_(h,['원본파일'])},rows=[],stats={},p=0;
 for(var r=hr+1;r<v.length;r++){var z=v[r],no=i73T_(z[x.order]);if(!no)continue;var st=i73T_(z[x.status]).toUpperCase(),amt=i73N_(z[x.purchase]);stats[st]=(stats[st]||0)+1;p+=amt;rows.push({business:i73T_(z[x.business]),account:i73T_(z[x.account]),orderDate:i73D_(z[x.date]),orderNo:no,purchase:amt,payment:x.payment>=0?i73T_(z[x.payment]):'',status:st,reason:x.reason>=0?i73T_(z[x.reason]):'',company:x.company>=0?i73T_(z[x.company]):'',cardName:x.name>=0?i73T_(z[x.name]):'',cardNumber:x.number>=0?i73T_(z[x.number]):'',end4:x.end4>=0?i73T_(z[x.end4]):'',approvalDate:x.adate>=0?i73D_(z[x.adate]):'',approvalNo:x.approval>=0?i73T_(z[x.approval]):'',approvalAmount:x.aamount>=0?i73N_(z[x.aamount]):0,merchant:x.merchant>=0?i73T_(z[x.merchant]):'',source:x.source>=0?i73T_(z[x.source]):''});}return {rows:rows,stats:stats,purchase:Math.round(p)};}
function i73GuardCard_(x){if(x.rows.length!==1355||(x.stats.MATCHED||0)!==808||(x.stats.NON_CARD||0)!==498||(x.stats.AMBIGUOUS||0)!==0||(x.stats.NO_MATCH||0)!==49||x.purchase!==105762969)throw new Error('운영 카드검증 exact guard 실패');}
function i73UsedSet_(rows){var u={};rows.forEach(function(o){if(o.status!=='MATCHED'&&o.status!=='NON_CARD')return;var k=i73EvidenceKey_(o.company,o.approvalNo,o.approvalDate,o.approvalAmount,o.merchant,o.source);if(k)u[k]=(u[k]||0)+1;});return u;}
function i73ReadHist_(s){var v=s.getDataRange().getValues(),hr=i73Header_(v,['카드사','승인금액']);if(hr<0)hr=0;var h=v[hr],x={company:i73Ix_(h,['카드사']),name:i73Ix_(h,['카드명']),number:i73Ix_(h,['카드번호']),end4:i73Ix_(h,['카드번호끝4']),date:i73Ix_(h,['승인일','이용일','거래일']),merchant:i73Ix_(h,['가맹점명','이용가맹점']),amount:i73Ix_(h,['승인금액','이용금액','거래금액']),approval:i73Ix_(h,['승인번호']),status:i73Ix_(h,['승인상태','승인/취소구분','상태']),cancelAmount:i73Ix_(h,['취소금액']),evidence:i73Ix_(h,['증빙유형']),lotte:i73Ix_(h,['롯데계열여부']),source:i73Ix_(h,['원본파일'])},a=[];for(var r=hr+1;r<v.length;r++){var z=v[r],date=i73D_(z[x.date]),amt=i73N_(z[x.amount]);if(!date&&!amt)continue;var q={row:r+1,company:x.company>=0?i73T_(z[x.company]):'',cardName:x.name>=0?i73T_(z[x.name]):'',cardNumber:x.number>=0?i73T_(z[x.number]):'',end4:x.end4>=0?i73T_(z[x.end4]):'',date:date,merchant:x.merchant>=0?i73T_(z[x.merchant]):'',amount:amt,approvalNo:x.approval>=0?i73T_(z[x.approval]):'',status:x.status>=0?i73T_(z[x.status]):'',cancelAmount:x.cancelAmount>=0?i73N_(z[x.cancelAmount]):0,evidence:x.evidence>=0?i73T_(z[x.evidence]):'',lotte:x.lotte>=0?i73T_(z[x.lotte]):'',source:x.source>=0?i73T_(z[x.source]):''};q.nonCard=i73C_([q.company,q.cardName,q.evidence].join(' ')).match(/비카드|현금영수증|페이머니|머니/)!==null;q.cancel=i73Cancel_(q);q.lotteEvidence=i73T_(q.lotte).toUpperCase()==='Y'||/롯데|LOTTE/i.test(q.merchant);q.identity=q.nonCard?'NONCARD|'+i73C_(q.cardName||q.evidence):'CARD|'+i73C_(q.company)+'|'+i73C_(q.cardNumber||q.end4||q.cardName);q.key=i73EvidenceKey_(q.company,q.approvalNo,q.date,q.amount,q.merchant,q.source);a.push(q);}return a;}
function i73Diag_(o,h,u){if(!o.purchase)return i73Base_('ZERO','BLOCKED_ZERO');var candidates=h.filter(function(q){return q.lotteEvidence&&!q.cancel&&q.amount===o.purchase&&Math.abs(i73Days_(o.orderDate,q.date))<=14&&!(i73Days_(o.orderDate,q.date)>=0&&i73Days_(o.orderDate,q.date)<=7);});if(candidates.length){var best=candidates.slice().sort(function(a,b){return Math.abs(i73Days_(o.orderDate,a.date))-Math.abs(i73Days_(o.orderDate,b.date));})[0],used=candidates.filter(function(q){return q.key&&u[q.key];}),ids={};candidates.forEach(function(q){ids[q.identity]=1;});var conflict=candidates.some(function(q){return i73PayConflict_(o.payment,q.company);}),v='';if(candidates.length===1&&!used.length&&!conflict)v='AUTO_SAFE_DATE_WINDOW';else if(used.length)v='USED_BY_OTHER';else if(conflict)v='PAYMENT_CONFLICT';else v='MULTI_CANDIDATE';return {bucket:'DATE_EXACT',verdict:v,lag:i73Days_(o.orderDate,best.date),candidateCount:candidates.length,unusedCount:candidates.length-used.length,usedCount:used.length,identityCount:Object.keys(ids).length,candidateType:best.nonCard?'NON_CARD':'CARD',candidateIdentity:best.identity,candidateDate:best.date,candidateAmount:best.amount,nearestAmount:'',amountDiff:0,diffRate:0,splitPairCount:0,splitIdentity:'',splitUsed:0,summary:i73Summ_(candidates)};}
 var within=h.filter(function(q){var d=i73Days_(o.orderDate,q.date);return q.lotteEvidence&&!q.cancel&&d>=0&&d<=7;});var canceled=h.filter(function(q){var d=i73Days_(o.orderDate,q.date);return q.lotteEvidence&&q.cancel&&Math.abs(q.amount)===o.purchase&&d>=0&&d<=7;});if(canceled.length&&!within.length){var b=i73Base_('CANCELED','BLOCKED_CANCELED');b.candidateCount=canceled.length;b.summary=i73Summ_(canceled);return b;}
 if(within.length){within.sort(function(a,b){return Math.abs(a.amount-o.purchase)-Math.abs(b.amount-o.purchase);});var n=within[0],pairs=[];for(var i=0;i<within.length;i++)for(var j=i+1;j<within.length;j++)if(within[i].amount+within[j].amount===o.purchase)pairs.push([within[i],within[j]]);var safePairs=pairs.filter(function(p){return p[0].identity===p[1].identity&&!(p[0].key&&u[p[0].key])&&!(p[1].key&&u[p[1].key]);});var verdict=safePairs.length===1?'AUTO_SAFE_SPLIT':'AMOUNT_REVIEW',sp=safePairs[0]||pairs[0];return {bucket:'AMOUNT_DIFF',verdict:verdict,lag:i73Days_(o.orderDate,n.date),candidateCount:within.length,unusedCount:within.filter(function(q){return !(q.key&&u[q.key]);}).length,usedCount:within.filter(function(q){return q.key&&u[q.key];}).length,identityCount:i73Ids_(within),candidateType:n.nonCard?'NON_CARD':'CARD',candidateIdentity:n.identity,candidateDate:n.date,candidateAmount:n.amount,nearestAmount:n.amount,amountDiff:Math.abs(n.amount-o.purchase),diffRate:o.purchase?Math.abs(n.amount-o.purchase)/o.purchase:0,splitPairCount:pairs.length,splitIdentity:sp?sp[0].identity:'',splitUsed:sp?((sp[0].key&&u[sp[0].key]?1:0)+(sp[1].key&&u[sp[1].key]?1:0)):0,summary:i73Summ_(within.slice(0,5))};}
 return i73Base_('OTHER','NO_CANDIDATE');}
function i73Base_(b,v){return {bucket:b,verdict:v,lag:'',candidateCount:0,unusedCount:0,usedCount:0,identityCount:0,candidateType:'',candidateIdentity:'',candidateDate:'',candidateAmount:'',nearestAmount:'',amountDiff:'',diffRate:'',splitPairCount:0,splitIdentity:'',splitUsed:0,summary:''};}
function i73PayConflict_(p,c){var a=i73C_(p),b=i73C_(c);if(!a||!b||/lpay|엘페이|토스|카카오/.test(a))return false;var keys=[['국민','국민'],['kb','kb'],['우리','우리'],['신한','신한'],['농협','농협'],['nh','nh'],['삼성','삼성'],['하나','하나'],['현대','현대'],['롯데','롯데']];for(var i=0;i<keys.length;i++)if(a.indexOf(keys[i][0])>=0)return b.indexOf(keys[i][1])<0;return false;}
function i73EvidenceKey_(c,a,d,m,mer,s){if(i73T_(a))return 'APP|'+i73C_(c)+'|'+i73C_(a);if(!d&&!m&&!mer&&!s)return '';return 'ROW|'+d+'|'+m+'|'+i73C_(mer)+'|'+i73C_(s);}
function i73Summ_(a){return a.slice(0,5).map(function(q){return [q.date,q.amount,q.identity,q.approvalNo,q.key].join('|');}).join(' / ');}
function i73Ids_(a){var x={};a.forEach(function(q){x[q.identity]=1;});return Object.keys(x).length;}
function i73Cancel_(q){var s=i73C_(q.status);if(q.amount<0)return true;if(!s)return false;if(s.indexOf('취소있음')>=0)return false;return s.indexOf('취소')>=0||s.indexOf('환불')>=0;}
function i73Write_(ss,rows){var s=ss.getSheetByName(I73_DETAIL)||ss.insertSheet(I73_DETAIL);s.clear();var h=['사업자등록번호','쿠팡계정ID','주문일','주문번호','주문매입금액','롯데결제수단','기존근거','진단버킷','판정','dayLag','후보수','미사용후보수','기사용후보수','identity수','후보유형','후보identity','후보일','후보금액','최근접금액','금액차이','차이율','splitPair수','splitIdentity','split기사용수','후보요약'];s.getRange(1,1,1,h.length).setValues([h]);if(rows.length)s.getRange(2,1,rows.length,h.length).setValues(rows);s.setFrozenRows(1);s.getRange(1,1,1,h.length).setFontWeight('bold');if(rows.length){s.getRange(2,5,rows.length,1).setNumberFormat('#,##0');s.getRange(2,18,rows.length,3).setNumberFormat('#,##0');s.getRange(2,21,rows.length,1).setNumberFormat('0.0%');}try{s.getRange(1,1,rows.length+1,h.length).createFilter();}catch(_e){}}
function i73Status_(ss,p){var s=ss.getSheetByName(I73_STATUS)||ss.insertSheet(I73_STATUS);s.clearContents();s.getRange(1,1,1,2).setValues([['항목','값']]);if(p.length)s.getRange(2,1,p.length,2).setValues(p);s.setFrozenRows(1);s.getRange(1,1,1,2).setFontWeight('bold');s.autoResizeColumns(1,2);}
function i73Header_(v,req){for(var r=0;r<Math.min(v.length,30);r++){var h=v[r]||[],ok=req.every(function(n){return i73Ix_(h,[n])>=0;});if(ok)return r;}return -1;}
function i73Ix_(h,n){var m={};(h||[]).forEach(function(v,i){m[i73C_(v)]=i;});for(var j=0;j<n.length;j++){var k=i73C_(n[j]);if(Object.prototype.hasOwnProperty.call(m,k))return m[k];}return -1;}
function i73T_(v){if(v===null||v===undefined)return '';if(Object.prototype.toString.call(v)==='[object Date]')return Utilities.formatDate(v,Session.getScriptTimeZone()||'Asia/Seoul','yyyy-MM-dd');return String(v).trim();}
function i73C_(v){return i73T_(v).toLowerCase().replace(/[\s_\-\/.()\[\]:]+/g,'');}
function i73N_(v){if(typeof v==='number')return isNaN(v)?0:v;var n=Number(String(v||'').replace(/,/g,'').replace(/[^0-9.\-]/g,''));return isNaN(n)?0:n;}
function i73D_(v){if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v.getTime()))return Utilities.formatDate(v,Session.getScriptTimeZone()||'Asia/Seoul','yyyy-MM-dd');var s=i73T_(v),m=s.match(/(20\d{2})[^0-9]?(\d{1,2})[^0-9]?(\d{1,2})/);return m?m[1]+'-'+('0'+m[2]).slice(-2)+'-'+('0'+m[3]).slice(-2):'';}
function i73Days_(a,b){var x=String(a||'').split('-'),y=String(b||'').split('-');if(x.length!==3||y.length!==3)return 99999;return Math.round((Date.UTC(+y[0],+y[1]-1,+y[2])-Date.UTC(+x[0],+x[1]-1,+x[2]))/86400000);}
function i73Sig_(s){var r=s.getLastRow(),c=s.getLastColumn();if(r<1||c<1)return r+'x'+c+':EMPTY';var v=s.getRange(1,1,r,c).getValues(),t=JSON.stringify(v,function(_k,x){if(Object.prototype.toString.call(x)==='[object Date]')return {d:x.getTime()};return x;});var b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,t,Utilities.Charset.UTF_8);return r+'x'+c+':'+b.map(function(x){var n=(x<0?x+256:x).toString(16);return n.length===1?'0'+n:n;}).join('');}
